import re

with open('public/index.html', 'r', encoding='utf-8') as f:
    content = f.read()

replacements = {
    'lang="en"': 'lang="fr"',
    'Discover Morocco: a cultural travel guide with a real world map, landmark markers, local images, city stories and culture.': 'Découvrez le Maroc : un guide de voyage culturel avec carte interactive, marqueurs, images locales, histoires de villes et culture.',
    'Discover Morocco | Culture & Travel': 'Découvrez le Maroc | Culture & Voyage',
    '<strong>Discover Morocco</strong>': '<strong>Découvrez le Maroc</strong>',
    '<small>Culture & Travel</small>': '<small>Culture & Voyage</small>',
    'Destinations</a>': 'Destinations</a>',
    'Map</a>': 'Carte</a>',
    'City Stories</a>': 'Histoires de Villes</a>',
    'Culture Cities</a>': 'Villes Culturelles</a>',
    'Culture</a>': 'Culture</a>',
    'Plan a Trip</a>': 'Planifier un Voyage</a>',
    'Morocco travel guide</p>': 'Guide de voyage au Maroc</p>',
    'A cultural journey through Morocco’s cities, coast, mountains and desert.': 'Un voyage culturel à travers les villes, la côte, les montagnes et le désert du Maroc.',
    'Explore nine Moroccan destinations with locally matched visuals, precise map markers, cultural context and practical highlights.': 'Explorez neuf destinations marocaines avec des visuels locaux adaptés, des repères précis sur carte, un contexte culturel et des infos pratiques.',
    'Explore destinations': 'Explorer les destinations',
    'View map': 'Voir la carte',
    'Visual identity': 'Identité visuelle',
    'Moroccan arch, zellige, desert dunes and green star.': 'Arc marocain, zellige, dunes du désert et étoile verte.',
    'Moroccan landmarks</p>': 'Sites emblématiques marocains</p>',
    'Explore Morocco through real landmark stories.': 'Explorez le Maroc à travers l\'histoire de lieux emblématiques réels.',
    'Each destination is connected to a specific cultural place: Jemaa el-Fna, Hassan II Mosque, Chouara Tannery, Chefchaouen medina, Erg Chebbi, Essaouira Port, Hassan Tower, Tangier Kasbah area and Aït Ben Haddou.': 'Chaque destination est liée à un lieu culturel spécifique : Jemaa el-Fna, la Mosquée Hassan II, la Tannerie Chouara, la médina de Chefchaouen, l\'Erg Chebbi, le port d\'Essaouira, la Tour Hassan, la Kasbah de Tanger et Aït Ben Haddou.',
    '<span>Destinations</span>': '<span>Destinations</span>',
    '<span>Regions</span>': '<span>Régions</span>',
    '<span>Local images</span>': '<span>Images locales</span>',
    'Choose your Morocco route': 'Choisissez votre itinéraire au Maroc',
    'Filter by travel style, open a city card, then jump directly to the correct map location.': 'Filtrez par style de voyage, ouvrez une carte de ville, puis sautez directement au bon emplacement sur la carte.',
    'Search</label>': 'Recherche</label>',
    'Search city, landmark or culture..."': 'Rechercher une ville, un lieu ou une culture..."',
    '>All</button>': '>Tout</button>',
    '>Imperial</button>': '>Impériale</button>',
    '>Coastal</button>': '>Côtière</button>',
    '>Mountain</button>': '>Montagne</button>',
    '>Desert</button>': '>Désert</button>',
    'Interactive map</p>': 'Carte interactive</p>',
    'World map with Morocco landmark markers': 'Carte du monde avec repères marocains',
    'Zoom, move around the world, and click the Morocco markers to discover each cultural landmark.': 'Zoomez, déplacez-vous sur le globe et cliquez sur les marqueurs du Maroc pour découvrir chaque site culturel.',
    'Morocco landmark map': 'Carte des sites marocains',
    'Click a marker or city card to open the exact place shown in the image.': 'Cliquez sur un marqueur ou une carte de ville pour ouvrir le lieu exact illustré.',
    '>World</button>': '>Monde</button>',
    '>Morocco markers</button>': '>Marqueurs du Maroc</button>',
    'City stories</p>': 'Histoires de villes</p>',
    'What every destination represents': 'Ce que représente chaque destination',
    'Each section explains the city, the exact scene used in the website, and cultural details such as heritage, food, crafts and travel tips.': 'Chaque section explique la ville, la scène exacte illustrée et les détails culturels (patrimoine, gastronomie, artisanat et conseils).',
    'Moroccan culture cities</p>': 'Villes culturelles marocaines</p>',
    'Culture by city and landmark': 'La culture par ville et par site',
    'Every city in this website has its own cultural identity, food, crafts, heritage and a marker on the map.': 'Chaque ville a sa propre identité culturelle, sa gastronomie, son artisanat, son patrimoine et son marqueur sur la carte.',
    'Moroccan culture</p>': 'Culture marocaine</p>',
    'More than beautiful places': 'Bien plus que de beaux paysages',
    'Morocco’s identity is visible in hospitality, architecture, artisan work, cuisine, music and the link between medina life, mountains and desert routes.': 'L\'identité du Maroc se reflète dans son hospitalité, son architecture, son artisanat, sa cuisine, sa musique et le lien entre la vie en médina, les montagnes et le désert.',
    'Zellige</h3>': 'Zellige</h3>',
    'Geometric tilework used in palaces, fountains and riads, symbolizing precision and traditional craftsmanship.': 'Mosaïque géométrique utilisée dans les palais, fontaines et riads, symbolisant la précision et le savoir-faire traditionnel.',
    'Mint tea</h3>': 'Thé à la menthe</h3>',
    'A daily gesture of welcome, often prepared slowly and served with care to guests.': 'Un geste quotidien de bienvenue, souvent préparé lentement et servi avec soin aux invités.',
    'Craft souks</h3>': 'Souks artisanaux</h3>',
    'Leather, carpets, copper, woodwork and ceramics connect Moroccan cities to centuries-old artisan knowledge.': 'Cuir, tapis, cuivre, menuiserie et céramique relient les villes marocaines à un savoir-faire ancestral.',
    'Gnawa & Amazigh roots</h3>': 'Racines Gnawa & Amazighes</h3>',
    'Music, language and oral traditions give each region its own cultural rhythm.': 'Musique, langue et traditions orales donnent à chaque région son propre rythme culturel.',
    'Medina life</h3>': 'La vie en médina</h3>',
    'Old cities are organized around gates, fountains, mosques, markets, narrow lanes and neighborhood workshops.': 'Les vieilles villes s\'organisent autour de portes, fontaines, mosquées, marchés, ruelles et ateliers de quartier.',
    'Moroccan cuisine</h3>': 'Cuisine marocaine</h3>',
    'Tagine, couscous, pastilla, harira, dates, olives and spices change from region to region.': 'Tajine, couscous, pastilla, harira, dattes, olives et épices varient d\'une région à l\'autre.',
    'Traditional dress</h3>': 'Habits traditionnels</h3>',
    'Djellabas, caftans, babouches and embroidered details reflect celebration, climate and local craft traditions.': 'Djellabas, caftans, babouches et broderies reflètent les célébrations, le climat et les traditions artisanales locales.',
    'Desert hospitality</h3>': 'Hospitalité du désert</h3>',
    'In Saharan regions, tea, music, storytelling and camp life express generosity and connection to the landscape.': 'Dans le Sahara, le thé, la musique, les contes et la vie de camp expriment la générosité et le lien au paysage.',
    'Trip planner</p>': 'Planificateur de voyage</p>',
    'Ask for a Morocco itinerary': 'Demandez un itinéraire au Maroc',
    'Send a Morocco itinerary request from the website. The request is prepared for delivery to <strong>mohamedamine.fasseh@e-polytechnique.ma</strong> when SMTP settings are configured.': 'Envoyez une demande d\'itinéraire au Maroc depuis le site. La demande est préparée pour être envoyée à <strong>mohamedamine.fasseh@e-polytechnique.ma</strong> lorsque SMTP sera configuré.',
    '<label>Name': '<label>Nom',
    'placeholder="Your name"': 'placeholder="Votre nom"',
    'placeholder="you@example.com"': 'placeholder="vous@exemple.com"',
    'Destination<select': 'Destination<select',
    'Message<textarea': 'Message<textarea',
    'placeholder="Tell us what kind of trip you want..."': 'placeholder="Dites-nous quel genre de voyage vous souhaitez..."',
    'Send itinerary request': 'Envoyer la demande d\'itinéraire',
    'Discover Morocco — Culture & Travel. A from-scratch full-stack web project.': 'Découvrez le Maroc — Culture & Voyage. Un projet web full-stack créé de zéro.',
    '<strong>Project</strong>': '<strong>Projet</strong>',
    'Interactive map</a>': 'Carte interactive</a>',
    '<strong>Made with</strong>': '<strong>Fait avec</strong>',
    'Destinations</p>': 'Destinations</p>',
}

for k, v in replacements.items():
    content = content.replace(k, v)

with open('public/index.html', 'w', encoding='utf-8') as f:
    f.write(content)

print("Translations applied to public/index.html")
